default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: forest_development

test:
  <<: *default
  database: forest_test

production:
  <<: *default
  database: forest_production
  username: forest
  password: <%= ENV['FOREST_DATABASE_PASSWORD'] %>
